### ISSUE TITLE
Could use `str.lstrip` instead of `removeprefix`

### ISSUE THREAD

**Issue by justanotherbyte** [jay3332/obsidian.py#11]
https://docs.python.org/3/library/stdtypes.html#str.lstrip

does pretty much the same thing and its part of 3.7+ instead of primarily 3.9

**Comment by asze17** [comment]
But is amogus

**Comment by asze17** [comment]
> lstrip removes individual characters
> it removes on_, but lstrip would remove n_o
> like n_objects would be affected

Jay
